version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

  publish:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker-compose build
            docker-compose up -d

workflows:
  version: 2
  simple_workflow:
    jobs:
      - build-and-test
    when:
      branches:
        only:
          - develop

  publish_and_deploy:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
      # - deploy:
      #     requires:
      #       - publish
    when:
      branches:
        only:
          - main
