version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  working_directory: ../fnbapi
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
        docker-username: DOCKER_HUB_USERNAME
        docker-password: DOCKER_HUB_PASSWORD
      # - run:
      #     name: Build and push Docker image
      #     command: |
      #       docker-compose build
      #       docker-compose up -d
      - run:
          name: Build and push Docker image to Docker Hub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t ceciliakhiew/sctp-java-devops:latest .
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            docker push ceciliakhiew/sctp-java-devops:latest

workflows:
  version: 2
  simple_workflow:
    jobs:
      - build-and-test
    when:
      branches:
        only:
          - develop

  publish_and_deploy:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
      # - deploy:
      #     requires:
      #       - publish
    when:
      branches:
        only:
          - develop
