version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    working_directory: ../fnbapi
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      # - run:
      #     name: Build and push Docker image
      #     command: |
      #       docker-compose build
      #       docker-compose up -d
      - run:
          name: Build and push Docker image to Docker Hub
          command: |
            docker build -t ceciliakhiew/sctp-java-devops:latest .
            docker push ceciliakhiew/sctp-java-devops:latest

  deploy:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a sctp-java
            heroku container:release web -a sctp-java

workflows:
  version: 2
  simple_workflow:
    jobs:
      - build-and-test
    when:
      branches:
        only:
          - develop
